[project]
name = "ot-literature"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "pyspark==3.5.7",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "numpy>=2.2.5",
    "pytest>=8.3.5",
    "spark-nlp>=5.5.3",
]

[tool.pytest.ini_options]
pythonpath = ["."]
